options:
  install_repository:
     type: string
     default: "deb https://archive.serverdensity.com/trusty/ all main"
     description: Server Density PPA
  install_keys:
     type: string
     default: "74371316"
     description: Server density ppa GPG KEY
  sd_account:
     type: string
     default:
  sd_apitoken:
     type: string
     default:
  log_level:
     type: string
     default: INFO
  plugin_directory:
     type: string
     default:

